base/urls.py
from django.urls import path
from . import views
urlpatterns =[
    path('',views.home,name='home'),
    path('rooms/<str:pk>/',views.rooms,name='rooms'),
    #path('product',views.product,name='product'),
    path('createroom',views.createroom,name='create-room'),
    path('updateroom/<str:pk>/',views.updateroom,name='update-room'),
    path('deleteroom/<str:pk>',views.deleteroom,name='deleteroom'),
    path('Userregister',views.Userregister,name='register'),
    path('login',views.Userlogin,name='login'),
    path('logout',views.Userlogout,name='logout'),
    path('delete_message/<str:pk1>/<str:pk2>',views.delete_message,name='delete_message'),
    path('edit_message/<str:pk1>/<str:pk2>/',views.edit_message,name='edit_message'),
    path('Profile/<str:pk>',views.userProfile,name='Profile'),
    path('topics',views.topics,name='topics'),
    path('recent-activity',views.activity,name="recent_activity"),
    path('edit-user<str:pk>',views.editUser,name='edit-user'),
    path('photos',views.get_photos,name='photos')

    
]
#test

cloneapp/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic (models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
    # Predefined fields inherited from User:
    # - username
    # - first_name
    # - last_name
    # - email
    # - password
    # - is_staff
    # - is_active
    # - date_joined
    # - last_login
                                                                                    
class Room(models.Model):
    host = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    # ForeignKey represents many to one field means one host can have multiple rooms
    topic= models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    # In the similar way one topic can have multiple rooms
    id = models.AutoField(primary_key=True)
    participants = models.ManyToManyField(User,related_name='participants',blank=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created','-updated']

    def __str__(self):
        return self.name
from django.core.validators import MinLengthValidator
class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField(null=False,blank=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body[:50]
    class Meta:
        ordering = ['-created','-updated',]
        # -created means reverse order of created
from cloudinary.models import CloudinaryField
class photo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,related_name="dp")
    image = CloudinaryField('image',default='o2pachscqy1o3ys4j0sw')
    


    



base/forms.py
from django.forms import ModelForm
from .models import Room,Message,User,photo

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body','room','user']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','email','password']
class PhotoForm(ModelForm):
    class Meta:
        model = photo
        fields = ['user','image']

base/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Room,Topic,Message,photo
from .forms import RoomForm,MessageForm,UserForm,PhotoForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required # for login is required for creating rooms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def home(request):
    # rooms=[
    # {'id':1,'name':'Python geeks'},
    # {'id':2,'name':'Lets C'},
    # {'id':3,'name':'Frontend masters'}
    # ]
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(Q(topic__name__icontains=q) |
                               Q(name__icontains=q) |
                               Q(description__icontains=q)) 
    topics = Topic.objects.all()[:5]
    rooms_count = rooms.count()
    room_messages = Message.objects.all()


    return render(request,'main.html',{'rooms':rooms,'topics':topics,'rooms_count':rooms_count,'room_messages':room_messages })

@login_required(login_url='login')
def rooms(request,pk):

    if request.user.is_authenticated: 
        room =Room.objects.get(id=pk)     
        participants = room.participants.all()
        room_messages = room.message_set.all()

        '''if request.method=="POST":
            print('this code is running')
            message_body = request.POST.get('body') 
            message = Message.objects.create(
                user = request.user,
                room = room,
                body = message_body
            )
            room.participants.add(request.user)
            context = {
                'user':request.user,
                'message':message,
                
            }
            print(f'message body : {message_body}')
            return render(request,'chat_messages_partial.html',context)'''
            
        return render(request,'rooms.html',{'room':room,'pk':pk,'room_messages':room_messages,'participants':participants})
    return redirect('/login')


@login_required(login_url='login')
def createroom(request):
    if not request.user.is_authenticated:
        return redirect('/login')
    # if True:
    # form = RoomForm(request.POST)
    topics = Topic.objects.all()


    if request.method=='POST':
        room_name = request.POST.get('room_name')
        # topic_name = request.POST.get('dropdown')
        topic = Topic.objects.get(name=request.POST.get('dropdown'))
        room_about = request.POST.get('room_about')
        form = RoomForm(data={

            'host':request.user,
            'name':room_name,
            'topic':topic,
            'description':room_about
        })
        print(request.user,room_name,topic,room_about,sep='\n')
        if form.is_valid() :
            form.save()
            messages.success(request,'Room created successfully!')
            

            # return redirect(f'/rooms/{room.id}')
        else:
            messages.error(request,'Something wrong happened!')
        return redirect('/')

    return render(request,'createroom.html',{'topics':topics})
@login_required(login_url='login')
def updateroom(request,pk):

    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    topics = Topic.objects.all()
    if request.user!=room.host and not request.user.is_superuser :
        messages.error(request,'You are not authenticated to perform the operation!!')
        return redirect('/')
    if request.method == 'POST':
        room_name = request.POST.get("room_name")
        room_about = request.POST.get("room_about")
        room_topic = Topic.objects.get(name=request.POST.get("dropdown"))
        form = RoomForm(data={
            'host':request.user,
            'name':room_name,
            'description':room_about,
            'topic':room_topic,
        },instance=room)

        if form.is_valid():
            form.save()
            return redirect(f"/rooms/{pk}")
        messages.error(request,"Something went wrong while updating the details!")
        return redirect("/")


    return render(request,'updateroom.html',{'form':form,'pk':pk,'room':room,'topics':topics})

def deleteroom(request,pk):
    room = Room.objects.get(id=pk)
    if request.method == 'POST':
        room.delete()
        return redirect('/')
    return render(request,'delete.html',{'obj':room,'pk':pk})



def Userlogin(request):
    page= 'login'
    if request.user.is_authenticated:
        return redirect('/')
    username=  request.POST.get('username')
    password1 = request.POST.get('password')
    if request.method=='POST':
        
        user = authenticate(request,username=username,password=password1)

        if user is not None:
            login(request,user)
            return redirect('/')

        else:
            messages.error(request,'User does not exists!')
            print('Something went wrong!!, user=',user)
        return redirect('/login')
    return render(request,'login.html',{'page':page})

@login_required(login_url='login')
def Userlogout(request):
    logout(request)
    return redirect('/')

def Userregister(request):
    if request.user.is_authenticated :
        return redirect('/')
    page = 'register'
    form = UserForm()
    if request.method == 'POST':
        
        
        form = UserForm(
            data={
            "first_name" : request.POST.get('firstname'),
            "last_name":request.POST.get('lastname'),
            "username":request.POST.get('username'),
            "password":request.POST.get('password'),
            "email":request.POST.get('email')

        }
        )
        print(request.POST.get('password'))
        
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.username = user.username.strip()
            user.set_password(request.POST.get('password'))
            user.save()
            login(request,user)
            print('user form is valid')
            return redirect('/')
        messages.error(request,'Something went wrong!')
        return render(request,'login.html')

    return render(request,'login.html',{'page':page,'form':form})
@login_required(login_url='login')
def edit_message(request,pk1,pk2):
    message = Message.objects.get(id=pk2)
    if message.user != request.user :
        return HttpResponse('Nahi hoga edit chal bhaag yahan see!!')
    form = MessageForm(instance=message)
    
    if request.method=='POST':
        form = MessageForm(request.POST,instance=message)
        if form.is_valid():
            form.save()
            return redirect(f'/rooms/{pk1}')
    return render(request,'edit-message.html',{'form':form,'pk1':pk1,'pk2':pk2})

@login_required(login_url='login')
def delete_message(request,pk1,pk2):
    
    message = Message.objects.get(id = pk2)
    if request.user == message.user or request.user.is_superuser:
        message.delete()
        return redirect(request.META.get('HTTP_REFERER','default-view'))
    return redirect(f'/rooms/{pk1}')
# def edit_message(request,pk1,pk2):
#     return HttpResponse('Edit your message here')

def userProfile(request,pk):
    user = User.objects.get(id=pk)
    room_messages = Message.objects.filter(user__id=pk)[:5]
    topics = Topic.objects.all()[:5]
    user_rooms = Room.objects.filter(host = user)

    

    return render(request,'userProfile.html',{'user':user,'room_messages':room_messages,'topics':topics,'user_rooms':user_rooms})

@login_required(login_url='login')
def topics(request):
    topics = Topic.objects.all()
    return render(request,'topics.html',{"topics":topics})

@login_required(login_url='login')
def activity(request):
    return render(request,'activity.html')

@login_required(login_url='login')
def editUser(request,pk):

    user1 = User.objects.get(id=pk)
    if request.user != user1 and not request.user.is_superuser:
        return redirect('/')
    else:

        if request.method == "POST":
            username = request.POST.get("username")
            email = request.POST.get("email")
            date_joined = user1.date_joined
            user_bio = request.POST.get("user_bio")
            anyUser = UserChangeForm(data={
                "username":username,
                "email":email,
                "date_joined":date_joined,
                "is_active":request.user.is_active,
                "is_staff":request.user.is_staff,
                "is_superuser":request.user.is_superuser,

            },instance = user1)

            image = request.FILES.get('image')
            photo_rec = photo.objects.get(user=user1)
            form = PhotoForm(data={
                "user":user1   
            },
            files ={
                "image":image
            },
            instance=photo_rec
            
            )
            if form.is_valid():
                form.save()
                print('image form is valid',f'user-name: {request.user.username}')
            else:
                print(form.errors)
            if anyUser.is_valid():
                
                anyUser.save()
                print("userform is valid")
                return redirect(f"Profile/{user1.id}")
            else :
                messages.error(request,"Something went wrong!") 
                print(anyUser.errors)
                return redirect("/")
        
    return render(request,'edit-user.html',{"user":user1})


def get_photos(request):
    photo_rec = photo.objects.get(user = request.user)

templates/activity-component.html
<!-- <h1>
    Recent Activity
</h1>
<div class="activity-messages">
    {% for message in room_messages %}
    {% if message.user == request.user %}
    You replied : <b>{{message}}</b> to <b>{{message.room}} </b> {{message.created|timesince}} ago <br><br>
    {% else %}
    <a href="/Profile/{{message.user.id}}" >@{{message.user}}</a> replied : <b>{{message}}</b> to <b>{{message.room}} </b> {{message.created|timesince}} ago <br><br>
    {% endif %}
    {% endfor %}
</div> -->


<div class="activities__header">
    <h2>Recent Activities</h2>
</div>

{% for message in room_messages %}
 <div class="activities__box">
  <div class="activities__boxHeader roomListRoom__header">
    <a href="{% url 'Profile' message.user.id %}" class="roomListRoom__author">
      <div class="avatar avatar--small active">
        <img src="https://randomuser.me/api/portraits/men/13.jpg" />
      </div>
      <p>
        @{{message.user}}
        <span>{{message.created|timesince}} ago</span>
      </p>
    </a>
    <div class="roomListRoom__actions">
      {% if request.user == message.user or request.user.is_superuser %}
      <a href="{% url 'delete_message' pk1=message.room.id pk2=message.id  %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>Remove</title>
          <path
            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
          ></path>
        </svg>
      </a>
      {% endif %}
    </div>
  </div>
  <div class="activities__boxContent">
    <p>replied to post “<a href="{% url 'rooms' message.room.id %}">{{message.room}}</a>”</p>
    <div class="activities__boxRoomContent">
      
      {{message}}
    </div>
  </div>
</div> 
{% endfor %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon" />
<script src="https://unpkg.com/htmx.org"></script>
<script src="https://unpkg.com/hyperscript.org@0.9.14"></script>
<script src="https://unpkg.com/htmx-ext-ws@2.0.2" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
<title>Socialpedia - Study with curious strangers!</title>
</head>

<body>
    {% if messages %}  
    <ul>
        {% for message in messages %}
        <li>
            {{message}}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <header class="header header--loggedIn" style="  position:fixed;
    width:100%;
    padding:15px;
    top:0;
    left:0;
    background:#696d97a1; 
    backdrop-filter: blur(10px);
    z-index: 1000;">
        <div class="container">
          <a href="/" class="header__logo">
            <img src="{% static 'assets/logo.svg' %}" />
            <h1>Socialpedia</h1>
          </a>
          <form class="header__search" action="/">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                </path>
              </svg>
              <input style="color:white;" name="q" placeholder="Search for rooms" />
            </label>
          </form>
          <nav class="header__menu">
            <!-- Not Logged In -->
            <!-- <a href="/login.html">
                <img src="./assets/avatar.svg" />
                <p>Account</p>
              </a> -->
    
            <!-- Logged In -->
            <div class="header__user">
            {% if request.user.is_authenticated %}
            <a href="{% url 'Profile' request.user.id %}">
              <div class="avatar avatar--medium active">
                <img src="{{ photo.image.url }}" />
              </div>
              
              {% if request.user.is_superuser %}
              <p>{{request.user.username}} <span style="color:red" >@{{request.user.username}}</span></p>
              {% else %}
              <p>{{request.user.username}} <span>@{{request.user.username}}</span></p>
              {% endif %}
            </a>  
            <button class="dropdown-button" >
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>chevron-down</title>
                <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
              </svg>
            </button>

            
          </div>
          
          <div class="dropdown-menu">
            <a href="settings.html" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>tools</title>
                <path
                  d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
                ></path>
              </svg>
              Settings</a
            >
            <a href="/logout" class="dropdown-link">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path
                  d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
                ></path>
                <path
                  d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
                ></path>
              </svg>
              Logout
            </a>
            {% else %}
            <a style="color: rgb(113 198 221);font-size:15px;" href="/login">


              <img src="{% static 'assets/avatar.svg' %}" />
                <p>Login</p>

            </a>
            {% endif %}
          </div>
            
          </nav>
        </div>
      </header>

    <!-- <a href="/" style="font-size:30px;font-weight:bold;">Socialpedia</a>
    {% if request.user.is_authenticated %}
    <p style="display:inline-block"><a href="/Profile/{{request.user.id}}">Hii, {{request.user.username}}</a></p>
    <a class="login-link" href="/logout">Logout</a>
    <form action="/">
        <br><input type="text" name="q" id="" placeholder="Search rooms">
        <input type="submit" value="Search">
    </form>
    {% else %}
    <a class="login-link" href="/login">Login</a>
    {% endif %} -->



    {% block content %}
    <!-- Content from other templates -->
    <script src="{% static 'js/style.js' %}">

    </script>
    
    {% endblock %}
</body>
</html>

templates/createroom.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!-- <head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>StudyBuddy - Find study partners around the world!</title>
</head> -->

<!-- <body> -->

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="index.html">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Study Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="/createroom" method="POST">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Room Name</label>
              <input required id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              <!-- <input required type="text" name="topic_name" id="room_topic" list="topic-list" /> -->
              <!-- <datalist id="topic-list"> -->
              <select required id="room_topic" name="dropdown" >
                <!-- <option value="">Select your topic</option> -->
                {% for topic in topics %}
                <option value="{{topic.name}}">{{topic.name}}</option>
                {% endfor %}
              </select>
              <!-- </datalist> -->

            </div>


            <div class="form__group">
              <label for="room_about">About</label>
              <textarea name="room_about" id="room_about" placeholder="Write about your study group (Optional)..."></textarea>
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="/">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>

  {% endblock %}
<!-- </body>

</html> -->

templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="{% url 'deleteroom' pk %}" method="POST" >
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input onclick="window.location.href='{{request.META.HTTP_REFERER}}'" class="btn btn--main" type="button" value="Cancel" />
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/style.js' %}"></script>
{% endblock %}

templates/edit-message.html
{% extends 'base.html' %}
{% block content %}

<form action="/edit_message/{{pk1}}/{{pk2}}/" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

templates/photo.html
{% block content %}

{% if photo %}
<img src="{{ photo.image.url }}" alt="">
{% else %}
<h1>No photo to show</h1>
{%  endif %}
{% endblock %}

templates/topics-component.html
<!-- <h1 style="color:black">Latest Topics</h1>
{% if topics %}
<ul class="topics__list"></ul>
<li>
    <a href="/?q=''" class="active">All <span>553</span></a>
</li>
{% for topic in topics %}
<li>
    <a href="/?q={{topic.name}}" class="active"> {{topic.name}} <span>5</span></a>
</li>
{% endfor %}
</ul>
{% else %}
No topics available!
{% endif %} -->


<div class="topics__header">
  <h2>Browse Topics</h2>
</div>

<ul class="topics__list">
  <li>
    <a href="{% url 'topics' %}" class="active">All <span>{{rooms.count}}</span></a>
  </li>
  {% for topic in topics %}       
  <li>
    <a href="/?q={{topic.name}}" class="active">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
  </li>
  {% endfor %}
</ul>

<a class="btn btn--link" href="/">
  More
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
    <title>chevron-down</title>
    <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
  </svg>
</a>






templates/topics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="/">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>Search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a  class="active">All <span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics %}
              <li>
                <a href="/?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
              </li>
              {% endfor %}
              
            </ul>
          </div>
        </div>
      </div>
    </main>

    <script src="script.js"></script>
{% endblock %}

templates/user-registration.html
{% extends 'base.html' %}
{% block content %}
<style>
    .form-container{
        margin-left:40px;
    }
</style>

<div class="form-container">
    <form method="POST" action="/register">
        {% csrf_token %}
        <h2>User Registration</h2>
        <label for="username">Enter a username :</label>
        <input type="text" name="username" id="" value="John Doe"><br>
        <label for="email">Enter your Email :</label>
        <input type="email" name="email" value="ujjwalmishra@gmail.com" id=""><br>
        <label for="password">Create a password : </label>
        <input type="password" name="password1" value="password1" id=""><br>
        <label for="password_confirm">Confirm your password :</label>
        <input type="password" name="password2" value="password2" id=""><br>
        <input type="submit" value="Register">
    </form>
</div>

{% endblock %}